[package]
name = "ray-tracer"
version = "0.1.0"
authors = ["Jake Cheek <jake@f-m.fm>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
